### ISSUE TITLE
allow usefull derivation

### ISSUE THREAD

**Issue by neu-rah** [0xPIT/encoder#22]
Hi!

can you please change the data members of your ClickEncoder class, or at least some members, to protected instead of private?

The private is invalidating all non-trivial derivations of the class. In my case I'm interested on peeking button state without consuming input, but the private classification makes derivation useless.

or at least add some member functions to read from the values.

thanks

P.S. I can do it myself and submit a PR as long as you tell me how you prefer: change access | add members

**Comment by soligen2010** [comment]
You may want to look at my fork of the library.  I has a number of bug fixes and enhancements, including the change to protected.
