### ISSUE TITLE
solve [-wreorder] GCC warnings (Constructor initializer list)

### ISSUE THREAD

**Issue by Schallbert** [0xPIT/encoder#34]
Hi,

I have created a branch where I solved the -wreorder warnings due to intializer list and variable definition order variations between source and header files. Review should take <5min.
Couldn't push to remote due to permission restrictions. Would like to setup a pull request.
Thanks.

**Comment by gdbdzgd** [comment]
@Schallbert  this project seems   lost the owner's support  i have the same wreorder  issue, can u share your code? or fork the project to your zone.

**Comment by Schallbert** [comment]
[Forked](https://github.com/Schallbert/encoder) and fixed.
