### ISSUE TITLE
Compilation error with WITHOUT_BUTTON defined

### ISSUE THREAD

**Issue by jsleroy** [0xPIT/encoder#4]
Hello,

In the last revision of the Arduino branch, there is a compilation error when WITHOUT_BUTTON is defined:

```
ClickEncoder.h: In member function 'void ClickEncoder::setAccelerationEnabled(const bool&)': 
ClickEncoder.h:86:5: error: 'accelerationEnabled' was not declared in this scope
     accelerationEnabled = a;
```

To fix this issue, swap the lines 112/113 in ClickEncoder.h.

Before:

```
bool accelerationEnabled;
#endif
```

After:

```
#endif
bool accelerationEnabled;
```

**Comment by 0xPIT** [comment]
A fix by @andyhunti (Thanks!) has been merged on Jan, 15th.
